<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Polica
 */
class Polica extends Model
{
    protected $table = 'policas';

    public $timestamps = true;

    protected $fillable = [
        'osiguranikId',
        'osiguranikNaziv',
        'osiguranikIme',
        'osiguranikPrezime',
        'osiguranikOib',
        'osiguranikDatumRodjenja',
        'osiguranikSpolOznaka',
        'osiguranikUlica',
        'osiguranikKucniBroj',
        'osiguranikPostanskiBroj',
        'osiguranikNaselje',
        'osiguranikNaseljeOznaka',
        'osiguranikTelefon',
        'osiguranikEmail',
        'ugovarateljNaziv',
        'ugovarateljIme',
        'ugovarateljPrezime',
        'ugovarateljOib',
        'ugovarateljDatumRodjenja',
        'ugovarateljSpolOznaka',
        'ugovarateljUlica',
        'ugovarateljKucniBroj',
        'ugovarateljPostanskiBroj',
        'ugovarateljNaselje',
        'ugovarateljNaseljeOznaka',
        'ugovarateljTelefon',
        'ugovarateljEmail',
        'RanijeOsiguravajuceDrustvoSifra',
        'BrojRanijePolice',
        'RegistarskaOznaka',
        'Marka',
        'BrojSasije',
        'GodinaProizvodnje',
        'Snaga',
        'Zapremina',
        'Nosivost',
        'NrojPutnika',
        'Noja',
        'Proba',
        'TarifnaGrupaOznaka',
        'TarifnaPodGrupaOznaka',
        'TarifniPopustOznaka',
        'TarifniDoplatakOznaka',
        'OsiguranaSvota',
        'DatumPocetkaOsiguranja',
        'DatumIstekaOsiguranja',
        'TemeljnaPremija',
        'RezijskiDodatakOznaka',
        'BonusOznaka',
        'MalusOznaka',
        'AOPlusOmogoceno',
        'AOPlusOdabrano',
        'AOPlusPremija',
        'DjelomicniKaskoOmoguceno',
        'DjelomicniKaskoOdobreno',
        'DjelomicniKaskoPremija',
        'TarifniDoplatakIznos',
        'TarifniPopustIznos',
        'PosebniPopustOznaka',
        'ZonaOmoguceno',
        'ZonaOdabrano',
        'ZonaOznaka',
        'ZonaSvotaOznaka',
        'ZonaVrstaVozacaOznaka',
        'ZonaVrstaPutnikaOznaka',
        'AutoNezgodaOznakaPremijskeGrupe',
        'AutoNezgodaOsiguranaSvotaSmrt',
        'AutoNezgodaOsiguranaSvotaInvaliditet',
        'AutoNezgodaOsiguranaSvotaLijecenje',
        'AutoNezgodaPremija',
        'PorezTrosarinaPostotak',
        'PorezTrosarinaIznos',
        'Premija',
        'BrojZelenogKartona',
        'ZonaIznos',
        'ZonaOsiguranaSvota',
        'DatumIzdavanja',
        'PrikupljanjePodataka',
        'BrojPoliceBonus',
        'BrojPoliceBonusRazlog',
        'DatumPocetkaDugorocnogOsiguranja',
        'DatumIstekaDugorocnogOsiguranja',
        'OsobaZaObracunOznaka',
        'VozacOznaka',
        'KilometaraGodisnjeOznaka',
        'DatumIzdavanjeDozvole',
        'Kilometraza',
        'PopustViseVozilaOznaka',
        'PopustViseVozilaPostotak',
        'PopustViseVozilaIznos',
        'PopustViseVozilaOsnov',
        'PopustDugorocnoSifra',
        'PopustDugorocnoPostotak',
        'PopustDugorocnoIznos',
        'PopustKorporativniOznaka',
        'PopustKorporativniPostotak',
        'PopustKorporativniIznos',
        'NacinPlacanjaOznaka',
        'NacinPlacanjaPostotak',
        'NacinPlacanjaIznos',
        'NacinPlacanjaIznos2',
        'ZastitaBonusaOmoguceno',
        'ZastitaBonusaOdabrano',
        'ZastitaBonusaIznos',
        'ZastitaVozacaOmoguceno',
        'ZastitaVozacaOdabrano',
        'ZastitaVozacaIznos',
        'MjestoIzdavanja',
        'Napomena',
        'UvjetiOznaka',
        'Cjenik',
        'RanijiBonu',
        'PlacanjeIznosGotovinePrvaRata',
        'PlacanjeBrojObroka',
        'PlacanjeDatumDospijecaPrveRate',
        'SredstvaPlacanjaOznaka',
        'BankaKarticarOznaka',
        'BrojRacuna',
        'SerijskiBroj',
        'Naputak',
        'TehnickaKarakteristika'
    ];

    protected $guarded = [];

        
}